# fly.toml app configuration file generated for xivraidhistory on 2024-06-06T16:41:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xivraidhistory'
primary_region = 'ord'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]